type Query {
  dog: String
}

type Mutation {
  setDogName(name: String): Dog
  addDog(dog: DogInput): Dog
}

type Dog {
  name: String
  breed: String
}

input DogInput {
  name: String
  breed: String
}
